version: '3.8'

services:
  bot:
    build: .
    container_name: tg_video_bot
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
